language: node_js
node_js:
   - "node"

# safelist
branches:
  only:
  - master

script:
  - npm test

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  access: public
  on:
    branch: master

